#! /bin/sh

set -x

if [ $# -lt 4 ]; then
    echo Synopsis: $(basename $0) OUTPUT XRES YRES REFRESH_RATE
    exit 1
fi

OUTPUT=$1
XRES=$2
YRES=$3
RRATE=$4
MODENAME=${XRES}x${YRES}

xrandr --newmode $MODENAME $(gtf $XRES $YRES $RRATE | grep Modeline | cut -d ' ' -f 5-) 2>/dev/null
xrandr --addmode $OUTPUT $MODENAME
xrandr --output $OUTPUT --mode $MODENAME
